name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build
